// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkV3V_WNOxVlW83fjRpv9L2Nfqv4Yju6Q',
    appId: '1:859747488545:web:73568eb75a037d37746460',
    messagingSenderId: '859747488545',
    projectId: 'gradpro-64eee',
    authDomain: 'gradpro-64eee.firebaseapp.com',
    storageBucket: 'gradpro-64eee.firebasestorage.app',
    measurementId: 'G-EZ5NXZNWDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB4gtNLklxMkzByXKqwTdJ8nFxknkOrKA',
    appId: '1:859747488545:android:2631bf74c1e3cc62746460',
    messagingSenderId: '859747488545',
    projectId: 'gradpro-64eee',
    storageBucket: 'gradpro-64eee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Srjxdko2MFoD-OHzjq2nVmAsHZiNyXE',
    appId: '1:859747488545:ios:fd4297524ca31e57746460',
    messagingSenderId: '859747488545',
    projectId: 'gradpro-64eee',
    storageBucket: 'gradpro-64eee.firebasestorage.app',
    iosBundleId: 'com.example.gradProjectFlutterNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Srjxdko2MFoD-OHzjq2nVmAsHZiNyXE',
    appId: '1:859747488545:ios:fd4297524ca31e57746460',
    messagingSenderId: '859747488545',
    projectId: 'gradpro-64eee',
    storageBucket: 'gradpro-64eee.firebasestorage.app',
    iosBundleId: 'com.example.gradProjectFlutterNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkV3V_WNOxVlW83fjRpv9L2Nfqv4Yju6Q',
    appId: '1:859747488545:web:09d42e1df2a17ddb746460',
    messagingSenderId: '859747488545',
    projectId: 'gradpro-64eee',
    authDomain: 'gradpro-64eee.firebaseapp.com',
    storageBucket: 'gradpro-64eee.firebasestorage.app',
    measurementId: 'G-WRSVSVT2X2',
  );
}
